// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chair struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type ChairInput struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type Main struct {
	ID        string   `json:"id"`
	Title     string   `json:"title"`
	SubID     *int32   `json:"subId,omitempty"`
	SubObj    *string  `json:"subObj,omitempty"`
	Tools     []*Tool  `json:"tools,omitempty"`
	Tables    []*Table `json:"tables,omitempty"`
	Chairs    []*Chair `json:"chairs,omitempty"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
	DeletedAt *string  `json:"deletedAt,omitempty"`
}

type MainDelete struct {
	DeleteID string `json:"deleteId"`
}

type MainInput struct {
	ID     string        `json:"id"`
	Title  string        `json:"title"`
	SubID  *int32        `json:"subId,omitempty"`
	SubObj *string       `json:"subObj,omitempty"`
	Tools  []*ToolInput  `json:"tools,omitempty"`
	Tables []*TableInput `json:"tables,omitempty"`
	Chairs []*ChairInput `json:"chairs,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Table struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TableInput struct {
	Name string `json:"name"`
}

type Tool struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type ToolInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}
